

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=seaandtea_dev
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - seaandtea-network
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: seaandtea_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - seaandtea-network
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - seaandtea-network
  


volumes:
  postgres_data:

networks:
  seaandtea-network:
    driver: bridge
